root: true
parser: "@typescript-eslint/parser"

env:
    node: true
    es6: true

plugins:
    - prettier
    - "@typescript-eslint"

extends:
    - eslint:recommended
    - prettier
    - plugin:@typescript-eslint/recommended

parserOptions:
    ecmaVersion: 2022
    sourceType: module
